# Generated by Django 5.2.3 on 2025-09-10 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='accesorios',
            field=models.ManyToManyField(blank=True, related_name='producto_principal', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria'),
        ),
    ]
