# Generated by Django 5.2.3 on 2025-09-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_producto_accesorios_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='accesorios',
            field=models.ManyToManyField(blank=True, related_name='producto_principal', to='catalogo.producto', verbose_name='Refacciones'),
        ),
    ]
