# Generated by Django 5.2.3 on 2025-10-31 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_categoria_options_categoria_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('parent', 'nombre'), name='unique_subcategory_name'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('nombre',), name='unique_toplevel_category_name'),
        ),
    ]
